[target.x86_64-unknown-linux-musl]
pre-build = [
  "if command -v apk >/dev/null; then apk add --no-cache pkgconf alsa-lib-dev libxkbcommon-dev eudev-dev; elif command -v apt-get >/dev/null; then apt-get update && apt-get install -y pkg-config libasound2-dev libxkbcommon-dev libudev-dev; fi",
]
